<template>
  <section class="main">
    <div class="title">
      <h1 class="text-shadow-pop-br">
        <span>The</span>
        <br />Walrus
        <br />
        <span>and the</span>
        <br />Whistle
        <br />Blower
      </h1>

      <h3>A Film By Nathalie Bibeau</h3>

      <button class="button">Watch Trailer</button>
    </div>
    <div class="laurels">
      <img class="hd20" src="~assets/images/laurel.svg" alt />
      <!--<img class="hd20" src="~assets/images/laurel.svg" alt />-->
    </div>
  </section>
</template>

<script>
export default {};
</script>

<style scoped>
section {
  background: url("~assets/images/bg_pool_full.jpg");
  height: 100vh;
  width: 100%;
  background-position: center;
  background-size: cover;
}

.main {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  align-items: center;
  text-align: center;
  padding: 2.5rem;
}

.main .title {
  grid-column: 1;
}

.main .laurels {
  grid-column: 3;
}

h1 {
  font-size: 3rem;
  line-height: 1;
  color: rgba(50, 118, 134, 1);
  font-weight: 900;
  text-transform: uppercase;
  margin-bottom: 1rem;
  text-align: center;
  /*text-shadow: -1px 0 #ffffff, 0 1px #ffffff, 1px 0 #ffffff, 0 -1px #ffffff;*/
}

h1 span {
  font-weight: 300;
  font-size: 1.6rem;
  display: block;
  margin-bottom: -45px;
}

h3 {
  color: white;
  text-transform: uppercase;
  font-weight: 500;
  font-size: 1.2rem;
  letter-spacing: 1.1px;
  text-align: center;
}

.button {
  margin: 2rem;
  padding: 0.5rem 1rem;
  font: normal 700 1rem/1.5 "GTWalsheim";
  background: none;
  color: white;
  border: 2px solid white;
  text-transform: uppercase;
  cursor: pointer;
}

.hd20 {
  width: auto;
  height: 100px;
  padding: 0;
  margin: 0;
  display: block;
}

.laurels {
  display: flex;
  flex-direction: column;
}

.laurels img {
  margin: 0 1rem;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-4-5 23:52:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/*
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}

.fade-enter-active {
  -webkit-animation: text-focus-in 1.5s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
  animation: text-focus-in 1.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}*/

/* ----------------------------------------------
 * Generated by Animista on 2020-4-11 19:0:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/* ----------------------------------------------
 * Generated by Animista on 2020-4-11 19:7:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes text-shadow-pop-br {
  0% {
    text-shadow: 0 0 #fff, 0 0 #fff;
    -webkit-transform: translateX(0) translateY(0);
    transform: translateX(0) translateY(0);
  }
  100% {
    text-shadow: 1px 1px #fff, 2px 2px #fff;
    -webkit-transform: translateX(-2px) translateY(-2px);
    transform: translateX(-1px) translateY(-1px);
  }
}
@keyframes text-shadow-pop-br {
  0% {
    text-shadow: 0 0 #fff, 0 0 #fff;
    -webkit-transform: translateX(0) translateY(0);
    transform: translateX(0) translateY(0);
  }
  100% {
    text-shadow: 1px 1px #fff, 2px 2px #fff;
    -webkit-transform: translateX(-2px) translateY(-2px);
    transform: translateX(-2px) translateY(-2px);
  }
}

.text-shadow-pop-br {
  -webkit-animation: text-shadow-pop-br 3s both;
  animation: text-shadow-pop-br 3s both;
}

@media screen and (min-width: 620px) {
  h1 {
    font-size: 5.5rem;
    line-height: 1;
    /*text-shadow: 3px 3px rgba(255, 255, 255, 0.4);*/
  }

  h1 span {
    font-size: 1.3rem;
    margin-bottom: -80px;
    text-shadow: 1px 1px rgba(255, 255, 255, 0.4);
  }

  h3 {
    font-size: 1.5rem;
    letter-spacing: 1.1px;
  }
}

@media screen and (min-width: 1620px) {
  h1 {
    font-size: 8rem;
    line-height: 1;
  }

  h1 span {
    font-weight: 300;
    font-size: 4.2rem;
    margin-bottom: -95px;
  }

  h3 {
    font-size: 1.4rem;
    letter-spacing: 1.1px;
  }
}
</style>